packages: []
minimumReleaseAge: 10080
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar
  - semver
  - undici-types
  - '@hono/node-server'
allowBuilds:
  '@clerk/shared': true
  '@google/genai': true
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  browser-tabs-lock: true
  bufferutil: false
  core-js: false
  esbuild: true
  protobufjs: true
  utf-8-validate: false
