blank_issues_enabled: true
contact_links:
  - name: Questions & discussions
    url: https://github.com/Swastikdan/Pebbly/discussions
    about: Ask questions and discuss ideas that aren't bug reports or feature requests.
