/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as SearchRouteImport } from './routes/search'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as ApiMetaimageRouteImport } from './routes/api.metaimage'
import { Route as KeywordIdRouteImport } from './routes/keyword.$id'
import { Route as PersonIdRouteImport } from './routes/person.$id'
import { Route as CIdChar123SlugChar125RouteImport } from './routes/c.$id.{-$slug}'
import { Route as CollectionIdChar123SlugChar125RouteImport } from './routes/collection.$id.{-$slug}'
import { Route as ListTypeSlugRouteImport } from './routes/list.$type.$slug'
import { Route as MovieIdChar123SlugChar125IndexRouteImport } from './routes/movie/$id/{-$slug}/index'
import { Route as MovieIdChar123SlugChar125CastCrewRouteImport } from './routes/movie/$id/{-$slug}/cast-crew'
import { Route as MovieIdChar123SlugChar125MediaRouteImport } from './routes/movie/$id/{-$slug}/media'
import { Route as SeriesIdChar123SlugChar125IndexRouteImport } from './routes/series/$id/{-$slug}/index'
import { Route as SeriesIdChar123SlugChar125CastCrewRouteImport } from './routes/series/$id/{-$slug}/cast-crew'
import { Route as SeriesIdChar123SlugChar125MediaRouteImport } from './routes/series/$id/{-$slug}/media'
import { Route as SeriesIdChar123SlugChar125SeasonsRouteImport } from './routes/series/$id/{-$slug}/seasons'
import { Route as SeriesIdChar123SlugChar125SeasonSeasonNumberRouteImport } from './routes/series/$id/{-$slug}/season.$seasonNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/recommendations.lazy').then((d) => d.Route),
)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/search.lazy').then((d) => d.Route))
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/watchlist.lazy').then((d) => d.Route))
const ApiMetaimageRoute = ApiMetaimageRouteImport.update({
  id: '/api/metaimage',
  path: '/api/metaimage',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordIdRoute = KeywordIdRouteImport.update({
  id: '/keyword/$id',
  path: '/keyword/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdChar123SlugChar125Route = CIdChar123SlugChar125RouteImport.update({
  id: '/c/$id/{-$slug}',
  path: '/c/$id/{-$slug}',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIdChar123SlugChar125Route =
  CollectionIdChar123SlugChar125RouteImport.update({
    id: '/collection/$id/{-$slug}',
    path: '/collection/$id/{-$slug}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ListTypeSlugRoute = ListTypeSlugRouteImport.update({
  id: '/list/$type/$slug',
  path: '/list/$type/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdChar123SlugChar125IndexRoute =
  MovieIdChar123SlugChar125IndexRouteImport.update({
    id: '/movie/$id/{-$slug}/',
    path: '/movie/$id/{-$slug}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MovieIdChar123SlugChar125CastCrewRoute =
  MovieIdChar123SlugChar125CastCrewRouteImport.update({
    id: '/movie/$id/{-$slug}/cast-crew',
    path: '/movie/$id/{-$slug}/cast-crew',
    getParentRoute: () => rootRouteImport,
  } as any)
const MovieIdChar123SlugChar125MediaRoute =
  MovieIdChar123SlugChar125MediaRouteImport.update({
    id: '/movie/$id/{-$slug}/media',
    path: '/movie/$id/{-$slug}/media',
    getParentRoute: () => rootRouteImport,
  } as any)
const SeriesIdChar123SlugChar125IndexRoute =
  SeriesIdChar123SlugChar125IndexRouteImport.update({
    id: '/series/$id/{-$slug}/',
    path: '/series/$id/{-$slug}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SeriesIdChar123SlugChar125CastCrewRoute =
  SeriesIdChar123SlugChar125CastCrewRouteImport.update({
    id: '/series/$id/{-$slug}/cast-crew',
    path: '/series/$id/{-$slug}/cast-crew',
    getParentRoute: () => rootRouteImport,
  } as any)
const SeriesIdChar123SlugChar125MediaRoute =
  SeriesIdChar123SlugChar125MediaRouteImport.update({
    id: '/series/$id/{-$slug}/media',
    path: '/series/$id/{-$slug}/media',
    getParentRoute: () => rootRouteImport,
  } as any)
const SeriesIdChar123SlugChar125SeasonsRoute =
  SeriesIdChar123SlugChar125SeasonsRouteImport.update({
    id: '/series/$id/{-$slug}/seasons',
    path: '/series/$id/{-$slug}/seasons',
    getParentRoute: () => rootRouteImport,
  } as any)
const SeriesIdChar123SlugChar125SeasonSeasonNumberRoute =
  SeriesIdChar123SlugChar125SeasonSeasonNumberRouteImport.update({
    id: '/series/$id/{-$slug}/season/$seasonNumber',
    path: '/series/$id/{-$slug}/season/$seasonNumber',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/disclaimer': typeof DisclaimerRoute
  '/recommendations': typeof RecommendationsRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/api/metaimage': typeof ApiMetaimageRoute
  '/keyword/$id': typeof KeywordIdRoute
  '/person/$id': typeof PersonIdRoute
  '/c/$id/{-$slug}': typeof CIdChar123SlugChar125Route
  '/collection/$id/{-$slug}': typeof CollectionIdChar123SlugChar125Route
  '/list/$type/$slug': typeof ListTypeSlugRoute
  '/movie/$id/{-$slug}/cast-crew': typeof MovieIdChar123SlugChar125CastCrewRoute
  '/movie/$id/{-$slug}/media': typeof MovieIdChar123SlugChar125MediaRoute
  '/series/$id/{-$slug}/cast-crew': typeof SeriesIdChar123SlugChar125CastCrewRoute
  '/series/$id/{-$slug}/media': typeof SeriesIdChar123SlugChar125MediaRoute
  '/series/$id/{-$slug}/seasons': typeof SeriesIdChar123SlugChar125SeasonsRoute
  '/movie/$id/{-$slug}/': typeof MovieIdChar123SlugChar125IndexRoute
  '/series/$id/{-$slug}/': typeof SeriesIdChar123SlugChar125IndexRoute
  '/series/$id/{-$slug}/season/$seasonNumber': typeof SeriesIdChar123SlugChar125SeasonSeasonNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/disclaimer': typeof DisclaimerRoute
  '/recommendations': typeof RecommendationsRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/api/metaimage': typeof ApiMetaimageRoute
  '/keyword/$id': typeof KeywordIdRoute
  '/person/$id': typeof PersonIdRoute
  '/c/$id/{-$slug}': typeof CIdChar123SlugChar125Route
  '/collection/$id/{-$slug}': typeof CollectionIdChar123SlugChar125Route
  '/list/$type/$slug': typeof ListTypeSlugRoute
  '/movie/$id/{-$slug}/cast-crew': typeof MovieIdChar123SlugChar125CastCrewRoute
  '/movie/$id/{-$slug}/media': typeof MovieIdChar123SlugChar125MediaRoute
  '/series/$id/{-$slug}/cast-crew': typeof SeriesIdChar123SlugChar125CastCrewRoute
  '/series/$id/{-$slug}/media': typeof SeriesIdChar123SlugChar125MediaRoute
  '/series/$id/{-$slug}/seasons': typeof SeriesIdChar123SlugChar125SeasonsRoute
  '/movie/$id/{-$slug}': typeof MovieIdChar123SlugChar125IndexRoute
  '/series/$id/{-$slug}': typeof SeriesIdChar123SlugChar125IndexRoute
  '/series/$id/{-$slug}/season/$seasonNumber': typeof SeriesIdChar123SlugChar125SeasonSeasonNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/disclaimer': typeof DisclaimerRoute
  '/recommendations': typeof RecommendationsRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/api/metaimage': typeof ApiMetaimageRoute
  '/keyword/$id': typeof KeywordIdRoute
  '/person/$id': typeof PersonIdRoute
  '/c/$id/{-$slug}': typeof CIdChar123SlugChar125Route
  '/collection/$id/{-$slug}': typeof CollectionIdChar123SlugChar125Route
  '/list/$type/$slug': typeof ListTypeSlugRoute
  '/movie/$id/{-$slug}/cast-crew': typeof MovieIdChar123SlugChar125CastCrewRoute
  '/movie/$id/{-$slug}/media': typeof MovieIdChar123SlugChar125MediaRoute
  '/series/$id/{-$slug}/cast-crew': typeof SeriesIdChar123SlugChar125CastCrewRoute
  '/series/$id/{-$slug}/media': typeof SeriesIdChar123SlugChar125MediaRoute
  '/series/$id/{-$slug}/seasons': typeof SeriesIdChar123SlugChar125SeasonsRoute
  '/movie/$id/{-$slug}/': typeof MovieIdChar123SlugChar125IndexRoute
  '/series/$id/{-$slug}/': typeof SeriesIdChar123SlugChar125IndexRoute
  '/series/$id/{-$slug}/season/$seasonNumber': typeof SeriesIdChar123SlugChar125SeasonSeasonNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/disclaimer'
    | '/recommendations'
    | '/search'
    | '/watchlist'
    | '/api/metaimage'
    | '/keyword/$id'
    | '/person/$id'
    | '/c/$id/{-$slug}'
    | '/collection/$id/{-$slug}'
    | '/list/$type/$slug'
    | '/movie/$id/{-$slug}/cast-crew'
    | '/movie/$id/{-$slug}/media'
    | '/series/$id/{-$slug}/cast-crew'
    | '/series/$id/{-$slug}/media'
    | '/series/$id/{-$slug}/seasons'
    | '/movie/$id/{-$slug}/'
    | '/series/$id/{-$slug}/'
    | '/series/$id/{-$slug}/season/$seasonNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/disclaimer'
    | '/recommendations'
    | '/search'
    | '/watchlist'
    | '/api/metaimage'
    | '/keyword/$id'
    | '/person/$id'
    | '/c/$id/{-$slug}'
    | '/collection/$id/{-$slug}'
    | '/list/$type/$slug'
    | '/movie/$id/{-$slug}/cast-crew'
    | '/movie/$id/{-$slug}/media'
    | '/series/$id/{-$slug}/cast-crew'
    | '/series/$id/{-$slug}/media'
    | '/series/$id/{-$slug}/seasons'
    | '/movie/$id/{-$slug}'
    | '/series/$id/{-$slug}'
    | '/series/$id/{-$slug}/season/$seasonNumber'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/disclaimer'
    | '/recommendations'
    | '/search'
    | '/watchlist'
    | '/api/metaimage'
    | '/keyword/$id'
    | '/person/$id'
    | '/c/$id/{-$slug}'
    | '/collection/$id/{-$slug}'
    | '/list/$type/$slug'
    | '/movie/$id/{-$slug}/cast-crew'
    | '/movie/$id/{-$slug}/media'
    | '/series/$id/{-$slug}/cast-crew'
    | '/series/$id/{-$slug}/media'
    | '/series/$id/{-$slug}/seasons'
    | '/movie/$id/{-$slug}/'
    | '/series/$id/{-$slug}/'
    | '/series/$id/{-$slug}/season/$seasonNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DisclaimerRoute: typeof DisclaimerRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SearchRoute: typeof SearchRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiMetaimageRoute: typeof ApiMetaimageRoute
  KeywordIdRoute: typeof KeywordIdRoute
  PersonIdRoute: typeof PersonIdRoute
  CIdChar123SlugChar125Route: typeof CIdChar123SlugChar125Route
  CollectionIdChar123SlugChar125Route: typeof CollectionIdChar123SlugChar125Route
  ListTypeSlugRoute: typeof ListTypeSlugRoute
  MovieIdChar123SlugChar125CastCrewRoute: typeof MovieIdChar123SlugChar125CastCrewRoute
  MovieIdChar123SlugChar125MediaRoute: typeof MovieIdChar123SlugChar125MediaRoute
  SeriesIdChar123SlugChar125CastCrewRoute: typeof SeriesIdChar123SlugChar125CastCrewRoute
  SeriesIdChar123SlugChar125MediaRoute: typeof SeriesIdChar123SlugChar125MediaRoute
  SeriesIdChar123SlugChar125SeasonsRoute: typeof SeriesIdChar123SlugChar125SeasonsRoute
  MovieIdChar123SlugChar125IndexRoute: typeof MovieIdChar123SlugChar125IndexRoute
  SeriesIdChar123SlugChar125IndexRoute: typeof SeriesIdChar123SlugChar125IndexRoute
  SeriesIdChar123SlugChar125SeasonSeasonNumberRoute: typeof SeriesIdChar123SlugChar125SeasonSeasonNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metaimage': {
      id: '/api/metaimage'
      path: '/api/metaimage'
      fullPath: '/api/metaimage'
      preLoaderRoute: typeof ApiMetaimageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keyword/$id': {
      id: '/keyword/$id'
      path: '/keyword/$id'
      fullPath: '/keyword/$id'
      preLoaderRoute: typeof KeywordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id/{-$slug}': {
      id: '/c/$id/{-$slug}'
      path: '/c/$id/{-$slug}'
      fullPath: '/c/$id/{-$slug}'
      preLoaderRoute: typeof CIdChar123SlugChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$id/{-$slug}': {
      id: '/collection/$id/{-$slug}'
      path: '/collection/$id/{-$slug}'
      fullPath: '/collection/$id/{-$slug}'
      preLoaderRoute: typeof CollectionIdChar123SlugChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/$type/$slug': {
      id: '/list/$type/$slug'
      path: '/list/$type/$slug'
      fullPath: '/list/$type/$slug'
      preLoaderRoute: typeof ListTypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id/{-$slug}/': {
      id: '/movie/$id/{-$slug}/'
      path: '/movie/$id/{-$slug}'
      fullPath: '/movie/$id/{-$slug}/'
      preLoaderRoute: typeof MovieIdChar123SlugChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id/{-$slug}/cast-crew': {
      id: '/movie/$id/{-$slug}/cast-crew'
      path: '/movie/$id/{-$slug}/cast-crew'
      fullPath: '/movie/$id/{-$slug}/cast-crew'
      preLoaderRoute: typeof MovieIdChar123SlugChar125CastCrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id/{-$slug}/media': {
      id: '/movie/$id/{-$slug}/media'
      path: '/movie/$id/{-$slug}/media'
      fullPath: '/movie/$id/{-$slug}/media'
      preLoaderRoute: typeof MovieIdChar123SlugChar125MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$id/{-$slug}/': {
      id: '/series/$id/{-$slug}/'
      path: '/series/$id/{-$slug}'
      fullPath: '/series/$id/{-$slug}/'
      preLoaderRoute: typeof SeriesIdChar123SlugChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$id/{-$slug}/cast-crew': {
      id: '/series/$id/{-$slug}/cast-crew'
      path: '/series/$id/{-$slug}/cast-crew'
      fullPath: '/series/$id/{-$slug}/cast-crew'
      preLoaderRoute: typeof SeriesIdChar123SlugChar125CastCrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$id/{-$slug}/media': {
      id: '/series/$id/{-$slug}/media'
      path: '/series/$id/{-$slug}/media'
      fullPath: '/series/$id/{-$slug}/media'
      preLoaderRoute: typeof SeriesIdChar123SlugChar125MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$id/{-$slug}/seasons': {
      id: '/series/$id/{-$slug}/seasons'
      path: '/series/$id/{-$slug}/seasons'
      fullPath: '/series/$id/{-$slug}/seasons'
      preLoaderRoute: typeof SeriesIdChar123SlugChar125SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$id/{-$slug}/season/$seasonNumber': {
      id: '/series/$id/{-$slug}/season/$seasonNumber'
      path: '/series/$id/{-$slug}/season/$seasonNumber'
      fullPath: '/series/$id/{-$slug}/season/$seasonNumber'
      preLoaderRoute: typeof SeriesIdChar123SlugChar125SeasonSeasonNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DisclaimerRoute: DisclaimerRoute,
  RecommendationsRoute: RecommendationsRoute,
  SearchRoute: SearchRoute,
  WatchlistRoute: WatchlistRoute,
  ApiMetaimageRoute: ApiMetaimageRoute,
  KeywordIdRoute: KeywordIdRoute,
  PersonIdRoute: PersonIdRoute,
  CIdChar123SlugChar125Route: CIdChar123SlugChar125Route,
  CollectionIdChar123SlugChar125Route: CollectionIdChar123SlugChar125Route,
  ListTypeSlugRoute: ListTypeSlugRoute,
  MovieIdChar123SlugChar125CastCrewRoute:
    MovieIdChar123SlugChar125CastCrewRoute,
  MovieIdChar123SlugChar125MediaRoute: MovieIdChar123SlugChar125MediaRoute,
  SeriesIdChar123SlugChar125CastCrewRoute:
    SeriesIdChar123SlugChar125CastCrewRoute,
  SeriesIdChar123SlugChar125MediaRoute: SeriesIdChar123SlugChar125MediaRoute,
  SeriesIdChar123SlugChar125SeasonsRoute:
    SeriesIdChar123SlugChar125SeasonsRoute,
  MovieIdChar123SlugChar125IndexRoute: MovieIdChar123SlugChar125IndexRoute,
  SeriesIdChar123SlugChar125IndexRoute: SeriesIdChar123SlugChar125IndexRoute,
  SeriesIdChar123SlugChar125SeasonSeasonNumberRoute:
    SeriesIdChar123SlugChar125SeasonSeasonNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
